select * from customer

--Q1. What is the total revenue generated by male vs. female customers? 

select gender , sum(purchase_amount) as revenue 
from customer 
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id , purchase_amount from customer
where discount_applied ='yes' and purchase_amount > = (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select top 5  item_purchased  , round(avg(review_rating),2) [Average Product Rating] 
from customer
group by item_purchased
order by avg(review_rating) desc 


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select  shipping_type , round(AVG(purchase_amount),2) as avg_purchase 
from customer 
where shipping_type in ('Express' , 'Standard')
group by shipping_type


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status , count(customer_id) as total_customers 
,round(sum(purchase_amount),2) as total_revenue
,round(avg(purchase_amount),2) as avg_spend
from customer
group by subscription_status 
order by total_revenue , avg_spend desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5
item_purchased , 
   ROUND(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased 
order by discount_rate desc 


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as(
  select customer_id , previous_purchases , 
  case 
  when previous_purchases = 1 then 'New'
   when previous_purchases between 2 and 20  then 'returning'
    else 'loyal'
    end as custumer_segment
  from customer
)

select custumer_segment , count(*)[Number of customers]
from customer_type 
group by custumer_segment
order by [Number of customers] desc

--Q8. What are the top 3 most purchased products within each category?

with item_counts as(
  select 
   category , 
   item_purchased ,
   count(customer_id) as total_orders,
   ROW_NUMBER() over(partition by category order by count(customer_id) desc ) as rn
  from customer
  group by category , item_purchased
)

select rn , category ,item_purchased  , total_orders
from item_counts 
where rn <=3
order by rn


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status


--Q10. What is the revenue contribution of each age group? 

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc
